name: build & deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    env:
      GHPagesToken: ${{ secrets.GH_Pages }}
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: npm install & build
      run: |
        npm install
        npm run build

    - name: Deploy to GH Pages
      run: |
        git config --global user.email "jamie.haywood@gmail.com"
        git config --global user.name "jamiehaywood"
        git remote set-url origin https://${GHPagesToken}@github.com/jamiehaywood/HeartsPointsTracker.git
        npm run deploy