name: Build and Deployment

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: NPM install
      run: npm install
    
    - name: NPM Build
      run: npm run build
      
    - name: Configure GIT
      run: |
        git config --global user.email "jamie.haywood@gmail.com"
        git config --global user.name "jamiehaywood"
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/jamiehaywood/HeartsPointsTracker
    
    - name: NPM Deploy
      run: npm run deploy
